export const sentences = [
  "Coding is a very good skill.",
  "How are you, buddy!",
  "React is a library of JavaScript, not a framework.",
  "Typing fast is a very useful skill in today's digital world.",
  "JavaScript asynchronous programming helps with a smooth UI experience.",
  "Frontend development requires both creativity and logic.",
  "Backend systems handle all the powerful processes behind the scenes.",
  "Keep practicing, and you will see improvement.",
  "An error means a new opportunity to learn.",
  "A good UI design makes users feel comfortable and engaged.",
  "Components in React can be reused, which saves time.",
  "There is a slight difference between a framework and a library.",
  "Today, GitHub has become like a developer's portfolio.",
  "Every developer should learn at least one backend language.",
  "Debugging teaches patience and develops logical thinking.",
  "JavaScript is single-threaded but powerful due to its event loop.",
  "DSA helps in cracking interviews.",
  "Practice typing daily to improve accuracy and speed.",
  "Learning new skills every day is the best way to grow.",
  "React Hooks make functional components more powerful and useful.",
  "Typing tests improve your thinking and reaction speed.",
  "Mobile-first design ensures your website looks good on all devices.",
  "Tailwind CSS makes designing fast and consistent.",
  "After every project, you become a stronger developer.",
  "Learning through projects is the most effective method.",
  "Coding is not just a skill, it's a superpower for creators.",
  "Consistency is the key to becoming a good developer.",
  "Learn something new every day to stay updated.",
  "Redux helps manage complex state in large React apps.",
  "Problem solving is the heart of programming.",
  "Writing clean code is a good habit.",
  "Writing comments is important for future understanding.",
  "Creating a portfolio website shows your creativity and confidence.",
  "Try building both frontend and backend to become fullstack.",
  "Every bug fixes a gap in your understanding.",
  "Use Google smartly, it’s the best tool for coders.",
  "On the internet, someone has already written the solution to your problem.",
  "Don't fear errors — they are your best teachers.",
  "Version control tools like Git are essential for teamwork.",
  "Without JavaScript, web development feels incomplete.",
  "React Router makes SPA apps smooth.",
  "Use `map()` and `filter()` wisely in JS to write clean code.",
  "Creating APIs in backend is a core skill.",
  "Security is also an important part of coding.",
  "Use environment variables to protect sensitive information.",
  "Try to always write DRY (Don't Repeat Yourself) code.",
  "Learning coding requires patience, practice, and passion.",
  "Every project teaches you something you didn’t know before.",
  "Never stop learning, because technology never stops.",
  "Teamwork in software development is as important as code.",
  "Typing just 5 minutes daily can greatly improve your productivity.",
];
