export const sentences = [
  "Coding bahut achi hoti hai.",
  "How are you buddy!.",
  "React is a library of JavaScript, not a framework.",
  "Typing fast is a very useful skill in today's digital world.",
  "JavaScript asynchronous programming helps with smooth UI experience.",
  "Frontend development requires both creativity and logic.",
  "Backend systems handle all the powerful processes behind the scenes.",
  "Practice karte raho, improvement dikhai dega.",
  "Error ka matlab hota hai seekhne ka ek naya chance.",
  "A good UI design makes users feel comfortable and engaged.",
  "React mein components reuse ho sakte hain which saves time.",
  "Framework aur library mein thoda sa difference hota hai.",
  "Aaj ke time mein GitHub ek portfolio jaisa ban gaya hai.",
  "Har developer ko at least ek backend language seekhni chahiye.",
  "Debugging patience seekhaata hai aur logical soch develop karta hai.",
  "JavaScript is single-threaded but powerful due to its event loop.",
  "DSA help karta hai interviews crack karne mein.",
  "Practice typing daily to improve accuracy and speed.",
  "Learning new skills daily is the best way to grow.",
  "React Hooks make functional components more powerful and useful.",
  "Typing tests improve your thinking and reaction speed.",
  "Mobile-first design ensures your website looks good on all devices.",
  "Tailwind CSS se design fast aur consistent ban jata hai.",
  "Har project ke baad aap aur strong developer bante ho.",
  "Learning through projects is the most effective method.",
  "Coding is not just skill, it's a superpower for creators.",
  "Consistency is the key to becoming a good developer.",
  "Har din kuch naya seekhna chahiye to stay updated.",
  "Redux helps manage complex state in large React apps.",
  "Problem solving is the heart of programming.",
  "Clean code likhna ek good habit hoti hai.",
  "Comments likhna important hota hai for future understanding.",
  "Portfolio website banaana shows your creativity and confidence.",
  "Try building both frontend and backend to become fullstack.",
  "Every bug fixes a gap in your understanding.",
  "Use Google smartly, it’s the best tool for coders.",
  "Internet pe har problem ka solution kisi ne likha hi hota hai.",
  "Don't fear errors — they are your best teachers.",
  "Version control tools like Git are essential for team work.",
  "JavaScript ke bina web development adhura lagta hai.",
  "React Router se SPA apps smooth ban jaate hain.",
  "Use `map()`, `filter()` wisely in JS to write clean code.",
  "Backend mein APIs create karna ek core skill hoti hai.",
  "Security bhi coding ka important part hota hai.",
  "Use environment variables to protect sensitive info.",
  "Try to write DRY (Don't Repeat Yourself) code always.",
  "Learning coding requires patience, practice, and passion.",
  "Every project teaches something you didn't know before.",
  "Never stop learning, technology kabhi rukta nahi.",
  "Teamwork in software development is as important as code.",
  "Typing daily 5 mins can improve your productivity a lot.",
];
